// salvia/dashboard-v8-svelte/src/dashboard/Layout.svelte
<script>
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { browser } from '$app/environment';
	import { open } from './provider/store';
	import Overlay from './provider/Overlay.svelte';
	import TopNavigation from './topnavigation/Index.svelte';
	import SideNavigation from './sidenavigation/Index.svelte';

	/*w-[calc(100%-16rem)] class get the remain width of the main tag from lg:viewport by dividing
	(the total width by the width of the side navigation component which is w-64 = 16rem)*/

	const style = {
		container: `bg-gray-100 h-screen overflow-hidden relative`,
		mainContainer: `flex flex-col h-screen pl-0 w-full lg:space-y-4 lg:w-[calc(100%-16rem)]`,
		main: `h-screen overflow-auto pb-36 pt-8 px-2 md:pb-8 md:pt-4 md:px-8 lg:pt-0`
	};

	if (browser) {
		page.subscribe(() => {
			// close side navigation when route changes when viewport is less than 1024px
			if (window.innerWidth < 1024) {
				$open = false;
			}
		});
	}

	onMount(() => {
		document.getElementsByTagName('body').item(0).removeAttribute('tabindex');
	});
</script>

<div class={style.container}>
	<div class="flex items-start">
		<Overlay />
		<SideNavigation mobilePosition="right" />
		<div class={style.mainContainer}>
			<TopNavigation />
			<main class={style.main}>
				<slot />
			</main>
		</div>
	</div>
</div>

// salvia/dashboard-v8-vue/src/dashboard/Layout.vue
<script setup>
import Overlay from './provider/Overlay.vue';
import DashboardProvider from './provider/Provider.vue';
import TopNavigation from './topnavigation/Index.vue';
import SideNavigation from './sidenavigation/Index.vue';
</script>

<template>
  <DashboardProvider>
    <div class="relative h-screen overflow-hidden bg-gray-100">
      <div class="relative h-screen overflow-hidden lg:rounded-2xl">
        <div class="flex items-start">
          <Overlay />
          <side-navigation mobile-position="right" />
          <div class="flex h-screen w-full flex-col pl-0 lg:w-99 lg:space-y-4">
            <top-navigation />
            <main
              class="h-screen overflow-auto px-2 pb-36 pt-8 md:px-8 md:pb-8 md:pt-4 lg:pt-0"
            >
              <slot />
            </main>
          </div>
        </div>
      </div>
    </div>
  </DashboardProvider>
</template>
